version: '3.3'

services:
  redis01:
    build: .
    container_name: redis01
    networks:
      - host
    env_file:
      - './env/master_variables.env'
    volumes:
      - ./logs/sentinel.log:/var/log/sentinel.log

  redis02:
    build: .
    container_name: redis02
    networks:
      - host
    env_file:
      - './env/slave_variables.env'
      # - './env/master_variables.env'
    volumes:
      - ./logs/sentinel.log:/var/log/sentinel.log

  redis03:
    build: .
    container_name: redis03
    networks:
      - host
    env_file:
      - './env/slave_variables.env'
      # - './env/master_variables.env'
    volumes:
      - ./logs/sentinel.log:/var/log/sentinel.log
  proxy:
    build: ./nginx_HA
    links:
       - redis01
       - redis02
       - redis03
    networks:
      - host
    ports:
      - '6379:6379'

networks:
  host:

